version: '3.8'

services:
  loadbalancer:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - redis
    networks:
      - loadbalancer-network

  backend1:
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - loadbalancer-network

  backend2:
    image: nginx:alpine
    ports:
      - "8082:80"
    networks:
      - loadbalancer-network

  backend3:
    image: nginx:alpine
    ports:
      - "8083:80"
    networks:
      - loadbalancer-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - loadbalancer-network
    command: redis-server --appendonly yes

networks:
  loadbalancer-network:
    driver: bridge
