apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-loadbalancer
  labels:
    app: go-loadbalancer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-loadbalancer
  template:
    metadata:
      labels:
        app: go-loadbalancer
    spec:
      containers:
      - name: loadbalancer
        image: docker.io/tusharxo/load-balancer-go:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-loadbalancer-service
spec:
  selector:
    app: go-loadbalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
